package com.xtei.tailorsys.model.VO;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cloth_consumption_view
 */

@Data
public class ClothConsumptionVO {
    /**
     * 编号
     * 数据库列名：consum_id
     */
    private Integer consumId;

    /**
     * 服装名称
     * 数据库列名：clothtype_name
     */
    private String clothtypeName;

    /**
     * 布料幅宽
     * 数据库列名：consum_width
     */
    private Double consumWidth;

    /**
     * 衫长
     * 数据库列名：shirt_length
     */
    private Double shirtLength;

    /**
     * 胸围
     * 数据库列名：bust
     */
    private Double bust;

    /**
     * 总肩宽
     * 数据库列名：shoulder_width
     */
    private Double shoulderWidth;

    /**
     * 袖长
     * 数据库列名：sleeve_length
     */
    private Double sleeveLength;

    /**
     * 袖口（手腕围）
     * 数据库列名：wrist_circum
     */
    private Double wristCircum;

    /**
     * 领围（颈围）
     * 数据库列名：neck_circum
     */
    private Double neckCircum;

    /**
     * 裤长
     * 数据库列名：pants_length
     */
    private Double pantsLength;

    /**
     * 胸高（乳长）
     * 数据库列名：chest_height
     */
    private Double chestHeight;

    /**
     * 裙长
     * 数据库列名：skirt_length
     */
    private Double skirtLength;

    /**
     * 腰围
     * 数据库列名：waist_circum
     */
    private Double waistCircum;

    /**
     * 臀围
     * 数据库列名：hipline
     */
    private Double hipline;

    /**
     * 膝围
     * 数据库列名：knee_circum
     */
    private Double kneeCircum;

    /**
     * 踝围（裤脚）
     * 数据库列名：ankle_circum
     */
    private Double ankleCircum;

    /**
     * 总长
     * 数据库列名：total_length
     */
    private Double totalLength;

    /**
     * 前腰节长
     * 数据库列名：FWL
     */
    private Double fwl;

    /**
     * 腰长（背长）
     * 数据库列名：back_length
     */
    private Double backLength;

    /**
     * 股臀高
     * 数据库列名：hip_height
     */
    private Double hipHeight;

    /**
     * 备注信息
     * 数据库列名：consum_note
     */
    private Double consumNote;

}