package com.xtei.tailorsys.model.VO;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.format.DateTimeFormat;
import com.alibaba.excel.annotation.write.style.ColumnWidth;
import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fabric_receive_view
 */

@Data
@ColumnWidth(20)
public class FabricReceiveInfoVO {
    /**
     * 编号
     * 数据库列名：far_id
     */
    @ColumnWidth(10)
    @ExcelProperty(value = "编号")
    private Integer farId;

    /**
     * 布料名称
     * 数据库列名：fabric_name
     */
    @ColumnWidth(40)
    @ExcelProperty(value = "布料名称")
    private String fabricName;

    /**
     * 供应商名称
     * 数据库列名：sup_name
     */
    @ExcelProperty(value = "供应商名称")
    private String supName;

    /**
     * 入库长度
     * 数据库列名：far_length
     */
    @ExcelProperty(value = "入库长度")
    private Double farLength;

    /**
     * 入库重量
     * 数据库列名：far_weight
     */
    @ExcelProperty(value = "入库重量")
    private Double farWeight;

    /**
     * 入库价格
     * 数据库列名：far_price
     */
    @ExcelProperty(value = "入库价格")
    private Double farPrice;

    /**
     * 入库日期
     * 数据库列名：far_date
     */
    @DateTimeFormat("yyyy年MM月dd日")
    @ExcelProperty("入库日期")
    private Date farDate;

    /**
     * 用户名称
     * 数据库列名：username
     */
    @ExcelProperty("入库人")
    private String username;

}