package com.xtei.tailorsys.model.VO;

import com.alibaba.excel.annotation.ExcelIgnore;
import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.format.DateTimeFormat;
import com.alibaba.excel.annotation.write.style.ColumnWidth;
import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_view
 */
@Data
@ColumnWidth(20)
public class OrderViewVO {
    /**
     * 订单编号
     * 数据库列名：order_id
     */
    @ColumnWidth(25)
    @ExcelProperty(value = "订单编号",index = 0)
    private String orderId;

    /**
     * 顾客编号
     * 数据库列名：customer_id
     */
    @ExcelIgnore
    private Integer customerId;

    /**
     * 顾客实围编号
     * 数据库列名：anthr_id
     */
    @ColumnWidth(10)
    @ExcelProperty(value = "量体表编号",index = 1)
    private Integer anthrId;

    /**
     * 服装类型编号
     * 数据库列名：clothtype_id
     */
    @ExcelIgnore
    private Integer clothtypeId;

    /**
     * 总金额
     * 数据库列名：total_amount
     */
    @ExcelProperty(value = "总金额",index = 5)
    private Double totalAmount;

    /**
     * 定做数量
     * 数据库列名：order_number
     */
    @ExcelProperty(value = "定做数量",index = 12)
    private Integer orderNumber;

    /**
     * 交货时间
     * 数据库列名：deadline
     */
    @ExcelProperty(value = "交货日期",index = 7)
    private Date deadline;

    /**
     * 订单创建时间
     * 数据库列名：created_time
     */
    @ColumnWidth(30)
    @DateTimeFormat("yyyy年MM月dd日HH时mm分ss秒")
    @ExcelProperty(value = "创建订单日期",index = 6)
    private Date createdTime;

    /**
     * 订单状态
     * 数据库列名：order_status
     */
    @ExcelProperty(value = "订单状态",index = 10)
    private Integer orderStatus;

    /**
     * 预交金额
     * 数据库列名：booked_amount
     */
    @ExcelProperty(value = "预交金额",index = 8)
    private Double bookedAmount;

    /**
     * 支付方式
     * 数据库列名：payment_method
     */
    @ExcelProperty(value = "支付方式",index = 9)
    private Integer paymentMethod;

    /**
     * 订单笔记
     * 数据库列名：order_note
     */
    @ColumnWidth(40)
    @ExcelProperty(value = "订单备注",index = 11)
    private String orderNote;

    /**
     * 订单名称
     * 数据库列名：order_name
     */
    @ExcelProperty(value = "订单名称",index = 2)
    private String orderName;

    /**
     * 服装名称
     * 数据库列名：clothtype_name
     */
    @ExcelProperty(value = "服装类型",index = 4)
    private String clothtypeName;

    /**
     * 顾客姓名
     * 数据库列名：customer_name
     */
    @ExcelProperty(value = "顾客名称",index = 3)
    private String customerName;

}