package com.xtei.tailorsys.entity;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table anthropometry_tb
 */
@Data
public class Anthropometry {
    /**
     * 编号
     * 数据库列名：anthr_id
     */
    private Integer anthrId;

    /**
     * 顾客编号
     * 数据库列名：customer_id
     */
    private Integer customerId;

    /**
     * 备注信息
     * 数据库列名：anthr_note
     */
    private String anthrNote;

    /**
     * 总体高
     * 数据库列名：overall_height
     */
    private Double overallHeight = 0.0;

    /**
     * 总长
     * 数据库列名：total_length
     */
    private Double totalLength = 0.0;

    /**
     * 头围
     * 数据库列名：head_circum
     */
    private Double headCircum = 0.0;

    /**
     * 颈围
     * 数据库列名：neck_circum
     */
    private Double neckCircum = 0.0;

    /**
     * 肩宽
     * 数据库列名：shoulder_width
     */
    private Double shoulderWidth = 0.0;

    /**
     * 胸宽
     * 数据库列名：chest_width
     */
    private Double chestWidth = 0.0;

    /**
     * 胸围
     * 数据库列名：bust
     */
    private Double bust = 0.0;

    /**
     * 背宽
     * 数据库列名：back_width
     */
    private Double backWidth = 0.0;

    /**
     * 背长
     * 数据库列名：back_length
     */
    private Double backLength = 0.0;

    /**
     * 腰长
     * 数据库列名：waist_length
     */
    private Double waistLength = 0.0;

    /**
     * 前腰节长
     * 数据库列名：FWL
     */
    private Double fwl = 0.0;

    /**
     * 胸高（乳长）
     * 数据库列名：chest_height
     */
    private Double chestHeight = 0.0;

    /**
     * 裙长
     * 数据库列名：skirt_length
     */
    private Double skirtLength = 0.0;

    /**
     * 乳宽
     * 数据库列名：breast_width
     */
    private Double breastWidth = 0.0;

    /**
     * 袖长
     * 数据库列名：sleeve_length
     */
    private Double sleeveLength = 0.0;

    /**
     * 内长
     * 数据库列名：inner_length
     */
    private Double innerLength = 0.0;

    /**
     * 裤长
     * 数据库列名：pants_length
     */
    private Double pantsLength = 0.0;

    /**
     * 衫长
     * 数据库列名：shirt_length
     */
    private Double shirtLength = 0.0;

    /**
     * 腰围
     * 数据库列名：waist_circum
     */
    private Double waistCircum = 0.0;

    /**
     * 腹围
     * 数据库列名：abdominal_circum
     */
    private Double abdominalCircum = 0.0;

    /**
     * 臀围
     * 数据库列名：hipline
     */
    private Double hipline = 0.0;

    /**
     * 股臀高
     * 数据库列名：hip_height
     */
    private Double hipHeight = 0.0;

    /**
     * 裆长
     * 数据库列名：crotch_length
     */
    private Double crotchLength = 0.0;

    /**
     * 手臂围
     * 数据库列名：arm_circum
     */
    private Double armCircum = 0.0;

    /**
     * 手臂根部围
     * 数据库列名：armroot_circum
     */
    private Double armrootCircum = 0.0;

    /**
     * 肘长
     * 数据库列名：elbow_length
     */
    private Double elbowLength = 0.0;

    /**
     * 手臂长
     * 数据库列名：arm_length
     */
    private Double armLength = 0.0;

    /**
     * 手腕围
     * 数据库列名：wrist_circum
     */
    private Double wristCircum = 0.0;

    /**
     * 掌围
     * 数据库列名：palm_circum
     */
    private Double palmCircum = 0.0;

    /**
     * 大腿围
     * 数据库列名：thigh_circum
     */
    private Double thighCircum = 0.0;

    /**
     * 膝盖围
     * 数据库列名：knee_circum
     */
    private Double kneeCircum = 0.0;

    /**
     * 踝围
     * 数据库列名：ankle_circum
     */
    private Double ankleCircum = 0.0;

    /**
     * 膝长
     * 数据库列名：knee_length
     */
    private Double kneeLength = 0.0;

    /**
     * 下体长
     * 数据库列名：lowerbody_length
     */
    private Double lowerbodyLength = 0.0;

    /**
     * 测量时间
     * 数据库列名：measure_time
     */
    private Date measureTime;

}