package com.xtei.tailorsys.entity;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fabric_tb
 */
@Data
public class FabricInfo {
    /**
     * 布料编号
     * 数据库列名：fabric_id
     */
    private Integer fabricId;

    /**
     * 布料名称
     * 数据库列名：fabric_name
     */
    private String fabricName;

    /**
     * 布料类型
     * 数据库列名：fabric_type
     */
    private Integer fabricType;

    /**
     * 布料幅宽
     * 数据库列名：fabric_width
     */
    private Double fabricWidth;

    /**
     * 布料图片URL
     * 数据库列名：fabric_url
     */
    private String fabricUrl;

}