package com.xtei.tailorsys.entity;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.write.style.ColumnWidth;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table suppliers_tb
 */
@Data
@ColumnWidth(20)
public class Supplier {
    /**
     * 供应商编号
     * 数据库列名：sup_id
     */
    @ColumnWidth(10)
    @ExcelProperty(value = "供应商编号")
    private Integer supId;

    /**
     * 供应商名称
     * 数据库列名：sup_name
     */
    @ColumnWidth(30)
    @ExcelProperty(value = "供应商名称")
    private String supName;

    /**
     * 供应商地址
     * 数据库列名：sup_address
     */
    @ColumnWidth(35)
    @ExcelProperty(value = "供应商地址")
    private String supAddress;

    /**
     * 供应商电话1
     * 数据库列名：sup_phone1
     */
    @ExcelProperty(value = "供应商联系电话-1")
    private String supPhone1;

    /**
     * 供应商电话2
     * 数据库列名：sup_phone2
     */
    @ExcelProperty(value = "供应商联系电话-2")
    private String supPhone2;

    /**
     * 供应商状态
     * 数据库列名：sup_status
     */
    @ExcelProperty(value = "供应商状态")
    private Boolean supStatus;

}