package com.xtei.tailorsys.model;

import com.alibaba.excel.annotation.ExcelIgnore;
import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.write.style.ColumnWidth;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customers_tb
 */

@Data
@ColumnWidth(20)
public class Customer {
    /**
     * 顾客编号
     * 数据库列名：customer_id
     */
    @ExcelProperty(value = "顾客编号")
    private Integer customerId;

    /**
     * 顾客姓名
     * 数据库列名：customer_name
     */
    @ExcelProperty(value = "顾客姓名")
    private String customerName;

    /**
     * 顾客性别
     * 数据库列名：customer_sex
     */
    @ExcelProperty(value = "顾客性别")
    private String customerSex;

    /**
     * 顾客电话1
     * 数据库列名：customer_phone1
     */
    @ExcelProperty(value = "顾客联系电话-1")
    private String customerPhone1;

    /**
     * 顾客电话2
     * 数据库列名：customer_phone2
     */
    @ExcelProperty(value = "顾客联系电话-2")
    private String customerPhone2;

    /**
     * 顾客住址
     * 数据库列名：customer_address
     */
    @ColumnWidth(30)
    @ExcelProperty(value = "顾客住址")
    private String customerAddress;

    /**
     * 顾客状态
     * 数据库列名：customer_status
     */
    @ExcelProperty(value = "顾客状态")
    private Boolean customerStatus;
}