package com.xtei.tailorsys.model;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table event_tb
 */
@Data
public class Event {
    /**
     * 数据库列名：id
     */
    private Integer id;

    /**
     * 事件内容
     * 数据库列名：content
     */
    private String content;

    /**
     * 日期
     * 数据库列名：date
     */
    private Date date;

}