package com.xtei.tailorsys.model;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fabric_stock_tb
 */

@Data
public class FabricStockInfo {
    /**
     * 编号
     * 数据库列名：fas_id
     */
    private Integer fasId;

    /**
     * 布料编号
     * 数据库列名：fabric_id
     */
    private Integer fabricId;

    /**
     * 现有库存
     * 数据库列名：fas_stock
     */
    private Double fasStock;

    /**
     * 库存位置
     * 数据库列名：fas_position
     */
    private String fasPosition;

    /**
     * 预定用量
     * 数据库列名：fas_prede
     */
    private Double fasPrede;

    /**
     * 单位价格
     * 数据库列名：unit_price
     */
    private Double unitPrice;


}