package com.xtei.tailorsys.model;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fabric_used_tb
 */
@Data
public class FabricUsedInfo {
    /**
     * 布料出库编号
     * 数据库列名：fau_id
     */
    private Integer fauId;

    /**
     * 布料编号
     * 数据库列名：fabric_id
     */
    private Integer fabricId;

    /**
     * 使用长度
     * 数据库列名：used_length
     */
    private Double usedLength;

    /**
     * 使用日期
     * 数据库列名：used_time
     */
    private Date usedTime;

    /**
     * 订单编号
     * 数据库列名：order_id
     */
    private String orderId;
}