package com.xtei.tailorsys.model;

import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fabrictype_datainfo
 */

@Data
public class FabricType {
    /**
     * 编号
     * 数据库列名：fabrictype_id
     */
    private Integer fabrictypeId;

    /**
     * 布料类型名称
     * 数据库列名：fabrictype_name
     */
    private String fabrictypeName;

    /**
     * 布料用处
     * 数据库列名：fabrictype_category
     */
    private String fabrictypeCategory;

    /**
     * 说明
     * 数据库列名：fabrictype_note
     */
    private String fabrictypeNote;
}