package com.xtei.tailorsys.model;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fabric_receive_tb
 */
@Data
public class FabricReceiveInfo {
    /**
     * 编号
     * 数据库列名：far_id
     */
    private Integer farId;

    /**
     * 布料编号
     * 数据库列名：fabric_id
     */
    private Integer fabricId;

    /**
     * 供应商编号
     * 数据库列名：sup_id
     */
    private Integer supId;

    /**
     * 入库长度
     * 数据库列名：far_length
     */
    private Double farLength;

    /**
     * 入库重量
     * 数据库列名：far_weight
     */
    private Double farWeight;

    /**
     * 入库价格
     * 数据库列名：far_price
     */
    private Double farPrice;

    /**
     * 入库日期
     * 数据库列名：far_date
     */
    private Date farDate;

    /**
     * 入库人
     * 数据库列名：far_storekeeper
     */
    private Integer farStorekeeper;

}